### PR TITLE
Arbitrary Torznab support

### LINKED ISSUE #83: Prowlarr
I’m not sure if this is possible quite yet as prowlarr (https://github.com/Prowlarr/Prowlarr/releases/tag/v0.1.0.361) is in its infancy, but it seems to be a replacement for jackett.

### PR DESCRIPTION
**Pull request by mmgoodnow**
Closes #83 
Sort of unblocks #13

- [x] config file
- [x] cli args
- [x] deprecate jackett config options
- [x] ping all indexers on startup (is this necessary? Maybe it's just slowing things down with minimal benefit)
- [x] Standardize on a TS representation of a result
- [x] Parse RSS into said representation
- [ ] ~~Paging~~ actually we're gonna just pretend paging doesn't exist. Prowlarr defaults to 100 and jackett seems to just be unpaged, and 100 results for a query on a private tracker would be pretty high
- [x] abstract searching pipeline to work either in jackett or torznab mode
- [x] disable jackett mode if torznab is specified
- [ ] ~~handle nonce options supplied in real-time requests to the daemon~~ descoped, as I'm not sure anybody uses this feature. Will reconsider if I hear from someone
- [x] update README
- [x] deprecation logging for jackett mode 
- [x] remove/relax jackett startup validation and required options
- [x] proper urlencoding
- [x] fix redaction

### CODE REVIEW

**Comment by mmgoodnow** [comment]
Alrighty folks; Torznab support is ready for user testing! I'm going to leave this PR open for about a week, then merge if I don't hear about any bugs. 

Docker users: Please pull from the tag `torznab`
CLI users: please clone the repo, checkout the `torznab` branch, run `npm ci`, `npm link`, and then `npm link cross-seed`. 

How to use: Put a bunch of torznab urls in an array in the `torznab` key in your config, or use the -T option on the command line, with torznab urls separated by spaces. See below for more info:

https://github.com/mmgoodnow/cross-seed/blob/f55398e3d44c7e0399039b235fb7e7de58a26af5/src/config.template.cjs#L29-L35

Check the verbose output for evidence that it's working, and please comment on this PR with your findings.

**Comment by DuzAwe** [comment]
Hey Just for clarity is it /1/api?apikey= or /1/?apikey=

**Comment by mmgoodnow** [comment]
The former. There should also be error handling to cover that

**Comment by mouzzampk2014** [comment]
Hi, might be ideal to handle the the config as it was before, like

```
	prowlarrServerUrl: "http://prowlarr:9696/prowlarr",
	prowlarrApiKey: "YOUR_PROWLARR_API_KEY_HERE```

Instead of adding api key after every tracker with long url.

As for url might be ideal to use ids and use alias i.e. 1=tracker1 or 2=tracker2. So there will be kor difference for end user.

I hope that clears few areas.

**Comment by DuzAwe** [comment]
Running in docker on Unraid and bare metal on a Pi.
Searching a lot (600) for testing looks likes its found stuff that with Jackett it had ignored.
All looks good, have it set up in daemon mode, Will keep an eye on that and report back should there be any issues but so far so good. Thanks once again for the hard work. 
There is already a issue open about it but getting the below node:17 error. 
 ```
"(node:17) [https://github.com/node-fetch/node-fetch/issues/1167] DeprecationWarning: form-data doesn't follow the spec and requires special treatment. Use alternative package
(Use `node --trace-deprecation ...` to show where the warning was created)"
```

**Comment by mouzzampk2014** [comment]
> Running in docker on Unraid and bare metal on a Pi. Searching a lot (600) for testing looks likes its found stuff that with Jackett it had ignored. All looks good, have it set up in daemon mode, Will keep an eye on that and report back should there be any issues but so far so good. Thanks once again for the hard work. There is already a issue open about it but getting the below node:17 error.
> 
> ```
> "(node:17) [https://github.com/node-fetch/node-fetch/issues/1167] DeprecationWarning: form-data doesn't follow the spec and requires special treatment. Use alternative package
> (Use `node --trace-deprecation ...` to show where the warning was created)"
> ```

Somehow this error is only related to unraid.

**Comment by mmgoodnow** [comment]
> Hi, might be ideal to handle the the config as it was before

I did consider that, but ultimately decided to go for this url-based implementation for the following reasons:
- because this approach consumes a well-defined API spec (Torznab), we get to support any trackers which implement Torznab directly, and we also get to support any other indexer management apps (jackett/prowlarr competitors) that might exist in the future, right out of the box
- doing it this way allows me to cover Jackett and Prowlarr with the same codepaths, and thus deprecate and eventually remove the existing Jackett-specific code (which consumes an unstable private api not intended for external use). For maintenance, the smaller the code ase, the better.
- I was concerned about the proliferation of config options and command line flags with that approach. I'd like to keep the number of options low so it isn't overwhelming to set up cross-seed, and also because lowercase letters for CLI flags are a very precious resource (there are only 26)

> As for url might be ideal to use ids and use alias i.e. 1=tracker1 or 2=tracker2. So there will be kor difference for end user.

I'm not sure I understand, though it seems like this might be a non-starter given the torznab url-based config.

**Comment by Jerrk** [comment]
I'm running on unraid with no issues so far in daemon mode.

i can also confirm that i've caught at least 50 cross-seedable torrents through prowlarr that jackett didn't pick up.

whilst the config situation isn't the most ideal since the numbering in the url doesnt correspond directly to an indexer but just the order that indexer was added in, when the template changes in prowlarr the url has to be updated in the cross-seed config.
though that is more of a prowlarr issue imo.

@mouzzampk2014 might be confused how prowlarr manages the indexers, the numbering corresponds to the order they were added so it would be unique to every person.
atleast thats how i understood it.

**Comment by DuzAwe** [comment]
Looks like in Daemon mode names are being sanitised of everything after S01E01. I can confirm two matches for the below, if I search in Prowlarr manually. 

```
cross-seed
info: [server] Received { name: 'The.Book.of.Boba.Fett.S01E01.1080p.HEVC.x265-MeGusta' }
info: [server] Found 0 torrents for { name: 'The.Book.of.Boba.Fett.S01E01.1080p.HEVC.x265-MeGusta' }
```
`Prowlarr | TorrentDay | The Book of Boba Fett S01E01 |   | 1:06am | 2922ms`

**Comment by mmgoodnow** [comment]
@DuzAwe that's working as designed in order to pull in more results from trackers with poor search functionality.

**Comment by DuzAwe** [comment]
@mmgoodnow Some other reason that its missed the match then. Shall I open an issue for this?

**Comment by mmgoodnow** [comment]
Are you sure it's actually a match?

**Comment by DuzAwe** [comment]
@mmgoodnow How can I run verbose for the daemon? Throws an error if it in the config.

**Comment by mmgoodnow** [comment]
@DuzAwe  what error? Regardless, verbose logging is always saved to log files even if it's not turned on.

**Comment by mmgoodnow** [comment]
@Byter09 that's a bug, thanks for uncovering.

**Comment by Byter09** [comment]
One more thing I noticed, maybe a bug, maybe intentional, I don't know: the Jackett API key and the qBittorrent password is being replaced by "[REDACTED]". This is not happening for API keys in the `torznab` array.

**Comment by Byter09** [comment]
> I'm getting this error when starting the container. Any idea's??
> 
> ```
>     SyntaxError: Unexpected token ':'
>     at wrapSafe (internal/modules/cjs/loader.js:1001:16)
>     at Module._compile (internal/modules/cjs/loader.js:1049:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
>     at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
>     at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
>     at async Loader.import (internal/modules/esm/loader.js:178:24)
>     at async getFileConfig (file:///usr/src/app/dist/configuration.js:32:17)
>     at async file:///usr/src/app/dist/cmd.js:34:20
> /config/config.js:10
> 		torznab: [ http://prowlarr:9696/7/api?apikey=REDACTED ]
> ```

Unsure if this is a bad copy, but it appears like your URL isn't put in quotation marks.

Try
```
torznab: [
    "http://prowlarr:9696/7/api?apikey=REDACTED",
],
```

**Comment by BaukeZwart** [comment]
Thanks @Byter09 that did the trick

**Comment by foux** [comment]
I'm having a `400 Bad Request` downloading all my torrents : 
```
error: error downloading torrent at https://my.torznab.site/8/download?apikey=[REDACTED]&link=UDU1SWcvZE13ODJKbkFSNVFCdVYzWTl6UGh0Z01ydXE5d1ZVVnEzZVVqYi80akplTCtOQXUzWTUwNzBtbVU5SWRHNTY4dGlhZERLUWNiL3J6SlA0cXBxMG5uM2Q0SGhxS3lYVldCd2lwQkE9&file=The+amazing+Spider-man-Le+destin+d%27un+héros+(2014)+Blu-ray+UHD+2160p+4KLight+10bits+HDR.MULTI.VOSTFR.VFF+DTS-HD+x265-baron: 400 Bad Request
```
But putting the URL in my browser downloads the torrents. Any idea?

**Comment by Byter09** [comment]
> I'm having a `400 Bad Request` downloading all my torrents :
> 
> ```
> error: error downloading torrent at https://my.torznab.site/8/download?apikey=[REDACTED]&link=UDU1SWcvZE13ODJKbkFSNVFCdVYzWTl6UGh0Z01ydXE5d1ZVVnEzZVVqYi80akplTCtOQXUzWTUwNzBtbVU5SWRHNTY4dGlhZERLUWNiL3J6SlA0cXBxMG5uM2Q0SGhxS3lYVldCd2lwQkE9&file=The+amazing+Spider-man-Le+destin+d%27un+héros+(2014)+Blu-ray+UHD+2160p+4KLight+10bits+HDR.MULTI.VOSTFR.VFF+DTS-HD+x265-baron: 400 Bad Request
> ```
> 
> But putting the URL in my browser downloads the torrents. Any idea?

Looking at the URL, not all special characters have been properly escaped (`héros` is what caught my eye). This might be a bug. Can you confirm that filenames without any special characters work?

Otherwise I hope I'm not diagnosing this wrong haha. Gotta wait for the maintainer to reply :)

**Comment by foux** [comment]
> Looking at the URL, not all special characters have been properly escaped (`héros` is what caught my eye). This might be a bug. Can you confirm that filenames without any special characters work?
> 
> Otherwise I hope I'm not diagnosing this wrong haha. Gotta wait for the maintainer to reply :)

Very well spotted, that's exactly it!

**Comment by bobokun** [comment]
Similar issue as @foux . Here's another example `failed to access http://prowlarr:9696/9/download?apikey=xxxx&link=xxxxxxx&file=More+Than+Blue+2018+1080p+BluRay+x264-WiKi+内封中文字幕`

**Comment by mmgoodnow** [comment]
Thanks for catching that bug!

**Comment by Byter09** [comment]
Watchtower automatically pulled the latest image, can confirm removing jackett stuff in the config works. API keys are also redacted (got an error with a tracker by pure coincidence :D). Wohoo!

**Comment by mmgoodnow** [comment]
In my testing, the URL-encoding seems to be causing trouble

**Comment by mmgoodnow** [comment]
@bobokun @foux can you test this out?

**Comment by Byter09** [comment]
> In my testing, the URL-encoding seems to be causing trouble

That would explain the 500 Internal Server error I'm getting from one of my trackers. but the URL looks fine so I can't tell.

**Comment by foux** [comment]
> @bobokun @foux can you test this out?

Unfortunately not tonight, I've got issues with my trackers and must leave! But I'll do that tomorrow morning!

**Comment by bobokun** [comment]
> @bobokun @foux can you test this out?

sure i'll continue to test

**Comment by foux** [comment]
> > @bobokun @foux can you test this out?
> 
> sure i'll continue to test. [EDIT]: Still seeing issues
> 
> ```
> 2022-01-06 16:59:02 �[31merror�[39m: failed to access http://prowlarr:9696/9/download?apikey=[REDACTED]&link=xxxxxxx&file=Escape+Room+Tournament+of+Champions+Extended+2021+720p+BluRay+x264-WiKi+*内封R3简繁中字++*Extended+Cut版
> 2022-01-06 16:59:02 �[34mdebug�[39m: Request path contains unescaped characters
> ```

Also got the issue, with URL like this : `https://prowlarr.tfdn.app/8/download?apikey=[REDACTED]&link=NkMvdytnTk8rZ3BVUXl6Z2VrSCtvcWtiMjBEdGZYcnJFVk9qZXhDc1lwQXdFOXFxSElmM1lmYjZjaGlhQkNtQSsxbWpCZzlGN043K0NQQ2pXdWNYZXd2T3cxYU0rRkZNdk9JbGJJV1k1czg9&file=Les+Schtroumpfs+-+Tome+39+-+Les+schtroumpfs+et+la+tempête+blanche+(2021)+Pdf`

**Comment by Byter09** [comment]
Here's another URL that ended in with a 404:

```
2022-01-07T18:13:23.234786513Z error: error downloading torrent at https://prowlarr.mydomain.tld/7/download?apikey=[REDACTED]&link=QWJHZHR6c3VSajllcThZeHlUTU5HNVNORERkZTNEQllTeHkzVDd5bnorZlhjWldweDNjZDU0UkZpZEZWbUU5UGM4U0syeUJNRExudXNkbVltU0s4M1lrUU5qcHhyL1dKa2NVZWY0ZnYzSk5hNCtMTUZBd3J3OVF1b0tPNWNQRHZUS2ZXbjF0OUR2QzN1c05IR0VQMlNBPT0&file=TheFatRat+-+MAYDAY+(Single)  %5B2018%2FFLAC%2FLossless%5D: 400 Bad Request
```

Original torrent name: `2018 - MAYDAY (Single)`

Hope this helps in figuring it out.

**Comment by newadventure079** [comment]
I typed in the help command in the wrong order and got this error
```
cross-seed search help
info: Validating your configuration...
warn: Jackett-only mode is deprecated and will be removed in a future release. Please specify your trackers using Torznab urls.
file:///volume1/homes/user/scripts/cross-seed/dist/torznab.js:22
    const urls = torznab.map((str) => new URL(str));
                         ^

TypeError: Cannot read property 'map' of undefined
    at validateTorznabUrls (file:///volume1/homes/user/scripts/cross-seed/dist/torznab.js:22:26)
    at doStartupValidation (file:///volume1/homes/user/scripts/cross-seed/dist/startup.js:20:9)
    at Command.<anonymous> (file:///volume1/homes/user/scripts/cross-seed/dist/cmd.js:135:15)
    at Command.listener [as _actionHandler] (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:488:17)
    at /volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:1193:19)
    at Command.parseAsync (/volume1/homes/user/scripts/cross-seed/node_modules/commander/lib/command.js:923:16)
```

**Comment by newadventure079** [comment]
It looks like it's iterating over individual episodes, even tho `includeEpisodes: false` is set

output:
```
cross-seed search --verbose --torrent-dir /volume1/data/Torrents/cross-seed/cross-seed-input/tmp/
verbose: [configdump] {
  trackers: [],
  torznab: [
    'http://172.17.0.1:9117/api/v2.0/indexers/iptorrents/results/torznab/api?apikey=[REDACTED]&amp;t=search&amp;cat=&amp;q='
  ],
  torrentDir: '/volume1/data/Torrents/cross-seed/cross-seed-input/tmp/',
  outputDir: '/volume1/data/Torrents/cross-seed/cross-seed-output',
  searchAll: false,
  fuzzySizeThreshold: 0.02,
  verbose: true,
  action: 'save',
  rtorrentRpcUrl: 'http://172.17.0.1:10000/RPC2',
  offset: 0,
  delay: 5,
  includeEpisodes: false
}
info: Validating your configuration...
verbose: [rtorrent] Calling method download_list with params []
info: Your configuration is valid!
info: Found 1 torrents, 1 suitable to search for matches
info: [1/1] Searching for 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb
verbose: [torznab] http://172.17.0.1:9117/api/v2.0/indexers/iptorrents/results/torznab/api?apikey=[REDACTED]&t=search&q=13+Reasons+Why+S02
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S01-S02 480p WEBRip nSD x264-NhaNc3 - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02 1080p NF WEBRip DD5 1 x264-NTb - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02 720p WEB x264-STRiFE [NO RAR] - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02 720p NF.WEBRip DD5 1 x264-NTb - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02 1080p WEB x264-STRiFE [NO RAR] - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E13 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E12 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E10 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E09 PROPER 720p HEVC x265-MeGusta - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E09 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E07 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E08 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E05 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E04 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E03 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E02 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E01 PROPER 1080p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E13 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E12 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E11 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E12 PROPER 720p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E10 PROPER READ NFO XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E10 PROPER READ NFO 720p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E09 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E08 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E07 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E11 REPACK 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E06 REPACK 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E06 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E05 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E04 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E04 PROPER 720p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E03 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E03 PROPER 720p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E02 PROPER XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E05 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E02 PROPER 720p WEBRip x264-WEBTiFUL - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E13 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E08 XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E01 XviD-AFG - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E11 720p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E09 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E10 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E08 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E01 1080p WEB x264-STRiFE - its size does not match (cached)
verbose: [decide] 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb - no match for IPTorrents torrent 13 Reasons Why S02E07 1080p WEB x264-STRiFE - its size does not match (cached)
info: Found 13.Reasons.Why.S02.2160p.NF.WEBRip.DD5.1.x264-NTb on IPTorrents
info: Done! Found 1 cross seeds from 1 original torrents
```

relevant part of config:
```
	// Whether to search for single episode torrents
	includeEpisodes: false,

	// search for all torrents, regardless of their contents
	// this option overrides includeEpisodes.
	searchAll: false,
```

**Comment by newadventure079** [comment]
@Jerrk It looks like you can add your own parameter to the torznab url so you can see which tracker it goes with since the ID numbering is pretty much worthless

`/1/api?apikey=[REDACTED]&tracker=AlphaRatio`

**Comment by newadventure079** [comment]
I've also had numerous `400 Bad Request` errors like other users have.

```
error: error downloading torrent at http://172.17.0.1:9696/24/download?apikey=[REDACTED]&link=link&file=Mouhitotsu+no+Afuganisutan%3A+Kabûru+nikki+1985+nen+AKA+Another+Afghanistan%3A+Kabul+Diary+1985+2003+Japan+%5BAnother.Afghanistan.Tsuchimoto.2003%5D: 400 Bad Request
debug: response:
debug: headers: {
  'content-length': '0',
  connection: 'close',
  date: 'Mon, 10 Jan 2022 08:07:03 GMT',
  server: 'Kestrel'
}
```

All of the `400 Bad Request` files had special chars in the name.  `é`, `ô`, etc

**Comment by mmgoodnow** [comment]
So it looks like the main remaining issue here is with special chars. @bakerboy448 can you take a look at this? I would expect a download link to already be URL-encoded. 

Has anyone found any 400s using any other non-Prowlarr torznab servers?

**Comment by mmgoodnow** [comment]
> It looks like it's iterating over individual episodes, even tho `includeEpisodes: false` is set

@newadventure079 It looks like it's checking search results that returned individual episodes, but the torrent it searched for in the first place looks like a season pack to me.

**Comment by mmgoodnow** [comment]
> I typed in the help command in the wrong order and got this error

what order?

**Comment by newadventure079** [comment]
> > I typed in the help command in the wrong order and got this error
> 
> @newadventure079 what order?

The order was in my original comment.  `cross-seed search help`

**Comment by mmgoodnow** [comment]
OK, I think we've gotten everything except the special characters in download links! However I think that those are a Prowlarr problem, not a cross-seed problem, per the URI RFC:. 

> 2.4.2. When to Escape and Unescape
> 
> **A URI is always in an "escaped" form, since escaping or unescaping a
   completed URI might change its semantics.**  Normally, the only time
   escape encodings can safely be made is when the URI is being created
   from its component parts; each component may have its own set of
   characters that are reserved, so only the mechanism responsible for
   generating or interpreting that component can determine whether or
   not escaping a character will change its semantics. Likewise, a URI
   must be separated into its components before the escaped characters
   within those components can be safely decoded.
> 
> In some cases, data that could be represented by an unreserved
   character may appear escaped; for example, some of the unreserved
   "mark" characters are automatically escaped by some systems.  If the
   given URI scheme defines a canonicalization algorithm, then
   unreserved characters may be unescaped according to that algorithm.
   For example, "%7e" is sometimes used instead of "~" in an http URL
   path, but the two are equivalent for an http URL.
> 
> Because the percent "%" character always has the reserved purpose of
   being the escape indicator, it must be escaped as "%25" in order to
   be used as data within a URI.  Implementers should be careful not to
   escape or unescape the same string more than once, since unescaping
   an already unescaped string might lead to misinterpreting a percent
   data character as another escaped character, or vice versa in the
   case of escaping an already escaped string.

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/releases/tag/v3.1.0

**Comment by foux** [comment]
@mmgoodnow so, in the merged version, If we defined both `torznab` and `trackers`, will it use the `torznab` indexers or the `Jackett` ones ?

**Comment by mmgoodnow** [comment]
Torznab takes precedence over the old jackett mode. If you still want to use trackers from jackett, you can use their torznab urls!

**Comment by foux** [comment]
> OK, I think we've gotten everything except the special characters in download links! However I think that those are a Prowlarr problem, not a cross-seed problem, per the [URI RFC](https://www.ietf.org/rfc/rfc2396.txt):

While I agree on a theoretical level, the URL is accepted in all the browsers I've tried. The issue is perhaps with `simple-get` which should accept such URLs....

**Comment by bakerboy448** [comment]
> > OK, I think we've gotten everything except the special characters in download links! However I think that those are a Prowlarr problem, not a cross-seed problem, per the [URI RFC](https://www.ietf.org/rfc/rfc2396.txt):
> 
> 
> 
> While I agree on a theoretical level, the URL is accepted in all the browsers I've tried. The issue is perhaps with `simple-get` which should accept such URLs....

Adding to this - it's UrlEncode function straight from dotnet System.Net library that is used

```
            var urlEncodedFile = WebUtility.UrlEncode(file);
            var proxyLink = $"{serverUrl}{urlBase}/{indexerId}/download?apikey={_configFileProvider.ApiKey}&link={encodedLink}&file={urlEncodedFile}";
```

https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urlencode

**Comment by mmgoodnow** [comment]
> While I agree on a theoretical level, the URL is accepted in all the browsers I've tried.

most browsers (not all though, at least the last time I checked. iPhone Safari doesn't) do implicit URL-encoding, which is probably why it's working in your browsers.

I just tried to download a torrent with `Cristóvão` in the name with `curl`, copying the download link straight from the Prowlarr UI and it 400ed. Even just the fact that the special characters still exist in the download URL seems fishy to me; it really looks like whatever URL encoding is supposed to happen _isn't_ happening somewhere. When I run that exact string through Javascript's `window.encodeURIComponent` function, I get `Crist%C3%B3v%C3%A3o`. @bakerboy448 is that code you pasted shared by all indexers? Or is that written on a per-indexer basis?

**Comment by bakerboy448** [comment]
that code is all indexers

regardless updated in nightly 

https://github.com/Prowlarr/Prowlarr/commit/a7b1ef19f57b8182c2ec3b105fe17d770add33d3
https://github.com/Prowlarr/Prowlarr/commit/6880f3863593244249bb0763ccf0d55d4240ed73
https://github.com/Prowlarr/Prowlarr/commit/2f22e7295cf705201bc74d371d3473426424f2d3

**Comment by mmgoodnow** [comment]
Thanks!

**Comment by newadventure079** [comment]
The `400` errors are gone for me with Prowlarr v0.2.0.1426

**Comment by bakerboy448** [comment]
> The `400` errors are gone for me with Prowlarr v0.2.0.1426

Yup, new develop cut today :)

**Pull request merged**
