### PR TITLE
v4

### LINKED ISSUE #13: RSS support
Since we're connected to Jackett, we have Torznab RSS feeds available to us. It would be nice to read RSS feeds every 10 or so minutes and compare them to existing torrents. 

xmljs is probably the best lib for this. 

This will be the slightly less useful half of daemon mode.

### LINKED ISSUE #69: Cache corruption
hi,

normaly i use this command
`cross-seed search --exclude-older 1440
`
this is my config.js

```
module.exports = {
	configVersion: 1,

	jackettServerUrl: "url",
	jackettApiKey: "api",
	delay: 5,
	trackers: ["trackers"],
	torrentDir: ".../rtorrent/session",
	outputDir: ".../.cross-seed/import",
	includeEpisodes: true,
	searchAll: true,

};
```

this usually works great as it just searches torrents which were added the last 24 hours.

i discovered that sometimes the --exclude-older flag is not working for me.
atm when i run the command i see this:

```
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 473 suitable to search for matches
[1/473] Searching for ...
```

i was expecting to search 2 torrents which i added an hour ago, other than the 2 torrent there were no torrents added to rtorrent in the last 48 hours,
why is cross-seed searching all my torrent?

this happened to me a few times before, the next day when i run the command everything works as expected again.

any idea what could cause this?

edit:
when i use  --exclude-older 120

```
cross-seed search --exclude-older 120
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 2 suitable to search for matches
[1/2] Searching for ...
```

it works fine

### LINKED ISSUE #164: Built-in cron
Is it possible to trigger search while in daemon mode?

### LINKED ISSUE #202: Switch cache to SQLite
when I run the cross seed script with many/all indexers I notice massive amounts of slowdown and constant ~80mb/s disk writes.
when I run int verbose mode I can clearly see that making decisions takes about a second, this isn't surprising given my cache.json is 82.8mb on disk. 
I could clear this cache.. but there are some trackers that have a daily limit of how many .torrents you can download. I'd also be pulling a few thousand torrents down every time I did this.

to me this seems like it really should be moved to an sqlite database, it's just a lot of overhead to process a large json like this.

### PR DESCRIPTION
**Pull request by mmgoodnow**
Cross-seed v4 is coming around the bend, and we've got some exciting improvements! I'm incredibly excited about finally shipping out-of-the-box RSS support. It has been on my mind since the first day I worked on cross-seed. 

## TODO
- [x] add warning about breaking changes to README
- [x] RSS mistakenly thinking things already exist in client? (thanks @Drazzilb08)
- [x] rss performance issues (thanks @Drazzilb08)
- [x] NPE on `something.id` (thanks to @KyleSanderson)
- [x] add breaking change info about timestamp exclusion flags
- [x] jobs do not resume when container restarts (thanks @Drazzilb08)
- [x] not finding torrents by criteria when hitting `/api/webhook` (thanks @BaukeZwart and @Davo1624)
- [x] write a migration guide

### Add support for periodic jobs like RSS scans
#242 - closes #13, closes #164 
- Use the new `rssCadence`/`--rss-cadence` option to do periodic RSS scans
  - enforced minimum of 10 minutes
  - supports the [vercel/ms format](https://github.com/vercel/ms)
- Use the new `searchCadence`/`--search-cadence` option to do periodic searches
  - enforced minimum of 1 day
  - supports the [vercel/ms format](https://github.com/vercel/ms)
### new `includeNonVideos`/`--include-non-videos` option
#243 (many thanks to @edgeworn!)
This option allows you to search for non-videos without having to also search for episodes.

### cache now uses SQLite
#220 - closes #202, closes #69 
We've simply outgrown the json cache. Some users with especially large torrent and tracker collections were experiencing weird bugs where the cache file would get corrupted occasionally, and others were just experiencing very heavy write volume because every time we needed to update a cache entry, we'd have to rewrite the entire cache file. 

I'm glad to set cross-seed's foundation on a rock-solid persistence layer. This also opens the door for a lot more improvements in the future (web UI, more filtering options) so stay tuned!

### `excludeOlder`/`--exclude-older` and `excludeRecentSearch`/`--exclude-recent-search` format changed
#245
These flags used to be specified in minutes but often users wanted to put values on the order of days. This required some math on the users' part, so I decided to change the format to be the [vercel/ms format](https://github.com/vercel/ms). When specifying in the config file, make sure to wrap in quotes. When specifying on the command line, make sure to either wrap in quotes or not include spaces (like `--exclude-older "10 mins"` or `--excludeOlder 10m`).

### `offset`/`--offset` removed 
#242
This was a vestige of the very first version of the script, which I added so that you could resume from where you left off if the program crashed due to an error during a long search. Since then, the program crashes much less and we've added timestamp filters which serve the use case. I had to remove it because it no longer makes any sense in the context of periodically-running jobs.

### Jackett-only mode removed
#245
The original implementation of cross-seed used Jackett's private JSON API. Now that we support Jackett through its public API (Torznab) we're deleting this hack.

#### Options removed
- `jackettServerUrl`/`--jackett-server-url`
- `jackettApiKey`/`--jackett-api-key`
- `trackers`/`--trackers`

### `searchAll`/`--search-all` argument and config option removed
#243
To get the same behavior, enable both `includeEpisodes`/`--include-episodes` and `allowNonVideos`/`--allow-non-videos`.

### CODE REVIEW

**Comment by mmgoodnow** [comment]
## Testing
Docker users: Please pull from the tag `v4`
CLI users: please clone the repo, checkout the `v4` branch, run npm ci, npm link, and then npm link cross-seed.

Please comment in this PR with any bugs you find!

**Comment by BaukeZwart** [comment]
I just updated to the latest v4 tag (commit 1c9d15824193042aa6aa105fdf0f14b3ecb0bb7d0), and I'm now getting the following error:
```~$ sudo docker exec cross-seed cross-seed search -r 1440 -x 14400
14400
Configuration file already exists.
info: Validating your configuration...
info: Your configuration is valid!

/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34
      const response = await statement.all(bindings);
                                       ^
SqliteError: select * from `searchee` where `name` = 'Bull.2016.S06E18.The.Other.Shoe.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv' limit 1 - database is locked
    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)
    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async filterTimestamps (file:///usr/src/app/dist/preFilter.js:42:30)
    at async Promise.all (index 0)
    at async filterAsync (file:///usr/src/app/dist/utils.js:62:21) {
  code: 'SQLITE_BUSY'
}

~$ sudo docker exec cross-seed cross-seed search -r 1440 -x 14400
14400
Configuration file already exists.
info: Validating your configuration...
info: Your configuration is valid!

/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34
      const response = await statement.all(bindings);
                                       ^
SqliteError: select * from `searchee` where `name` = 'Bull.2016.S06E18.The.Other.Shoe.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv' limit 1 - database is locked
    at Client_BetterSQLite3._query (/usr/src/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:34:40)
    at executeQuery (/usr/src/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_BetterSQLite3.query (/usr/src/app/node_modules/knex/lib/client.js:146:12)
    at Runner.query (/usr/src/app/node_modules/knex/lib/execution/runner.js:130:36)
    at ensureConnectionCallback (/usr/src/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
    at Runner.ensureConnection (/usr/src/app/node_modules/knex/lib/execution/runner.js:307:20)
    at async Runner.run (/usr/src/app/node_modules/knex/lib/execution/runner.js:30:19)
    at async filterTimestamps (file:///usr/src/app/dist/preFilter.js:42:30)
    at async Promise.all (index 0)
    at async filterAsync (file:///usr/src/app/dist/utils.js:62:21) {
  code: 'SQLITE_BUSY'
}

```

**Comment by BaukeZwart** [comment]
I'm having issues with daemon mode in v4.
I'm getting these errors every time a torrent is imported/upgraded and Sonarr triggers the daemon with a curl command.
```
2022-05-25 20:15:45 [32minfo[39m: [server] Received search request: { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
2022-05-25 20:15:45 [31merror[39m: could not find a torrent with the criteria { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
```
When I check qbit, the hash is correct and the same as the last torrent imported.
I see these errors after every import/upgrade.

**Comment by Davo1624** [comment]
> I'm having issues with daemon mode in v4. I'm getting these errors every time a torrent is imported/upgraded and Sonarr triggers the daemon with a curl command.
> 
> ```
> 2022-05-25 20:15:45 �[32minfo�[39m: [server] Received search request: { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
> 2022-05-25 20:15:45 �[31merror�[39m: could not find a torrent with the criteria { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
> ```
> 
> When I check qbit, the hash is correct and the same as the last torrent imported. I see these errors after every import/upgrade.

I am also experiencing the same issue

**Comment by BaukeZwart** [comment]
I'm using v4 now for about a week, but as far as I can see not one CS is added using RSS.
I run RSS every 15 min., and search daily.
All added CS are coming from search, none from RSS. I'm starting to wonder if RSS is even working as it is now.

**Comment by mmgoodnow** [comment]
> I'm using v4 now for about a week, but as far as I can see not one CS is added using RSS.
I run RSS every 15 min., and search daily.
All added CS are coming from search, none from RSS. I'm starting to wonder if RSS is even working as it is now.

I'm not sure either. I think there's a bug where it says that the torrent already exists when it tries to inject, which I'll work on  this weekend.

**Comment by mmgoodnow** [comment]
Ok, the "cannot destructure property `id` of (intermediate value) as it is null" issue should be fixed.

**Comment by mmgoodnow** [comment]
The `- exists` bug should be fixed now.

**Comment by mmgoodnow** [comment]
> I'm having issues with daemon mode in v4. I'm getting these errors every time a torrent is imported/upgraded and Sonarr triggers the daemon with a curl command.
> 
> ```
> 2022-05-25 20:15:45 �[32minfo�[39m: [server] Received search request: { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
> 2022-05-25 20:15:45 �[31merror�[39m: could not find a torrent with the criteria { infoHash: '0080fd2a54f4ab196db6d642c6a55fc407bbd153' }
> ```
> 
> When I check qbit, the hash is correct and the same as the last torrent imported. I see these errors after every import/upgrade.

this should be fixed as of the latest commit!

**Comment by BaukeZwart** [comment]
When running a manual search, the exclude-older argument isn’t used anymore.
When I run `docker exec cross-seed cross-seed search -x 1440` all original torrents are being searched.
I also tried `-x “1d”`, same result.

**Comment by BaukeZwart** [comment]
When doing a manual search and CS finds an already existing cross-seed it still sends notification for it. I would expect CS to only send notifications for newly added cross-seeds.

**Comment by thezak48** [comment]
Not sure if this is a me issue or a v4 issue but all I seem to be getting is this
`warn: Failed searching https://prowlarr.sm-dev.uk/12/api?apikey=[REDACTED] for The.King.in.Love.S01.2017.Disney+.WEB-DL.1080p.H264.AAC-HDCTV with reason: Error: Non-whitespace before first tag.`

**Comment by mmgoodnow** [comment]
> When running a manual search, the exclude-older argument isn’t used anymore.
When I run docker exec cross-seed cross-seed search -x 1440 all original torrents are being searched.
I also tried -x “1d”, same result.

what does the `excludeOlder` line in your configdump say?

**Comment by mmgoodnow** [comment]
> When doing a manual search and CS finds an already existing cross-seed it still sends notification for it. I would expect CS to only send notifications for newly added cross-seeds.

gonna call this one out of scope for v4, but it's definitely a valid feature request if you want to make one.

**Comment by BaukeZwart** [comment]
In the config I have set `excludeOlder: "14 days"`
Isn't `-x 1440` supposed to overwrite that?

**Comment by mmgoodnow** [comment]
Does anybody still have any outstanding bugs in v4?

**Comment by R3yn4ld** [comment]
> Does anybody still know of any outstanding bugs in v4?

Hi,

Went in production with V4, so far, so good, thanks for the great work !

**Pull request merged**
