### PR TITLE
Sqlite

### LINKED ISSUE #69: Cache corruption
hi,

normaly i use this command
`cross-seed search --exclude-older 1440
`
this is my config.js

```
module.exports = {
	configVersion: 1,

	jackettServerUrl: "url",
	jackettApiKey: "api",
	delay: 5,
	trackers: ["trackers"],
	torrentDir: ".../rtorrent/session",
	outputDir: ".../.cross-seed/import",
	includeEpisodes: true,
	searchAll: true,

};
```

this usually works great as it just searches torrents which were added the last 24 hours.

i discovered that sometimes the --exclude-older flag is not working for me.
atm when i run the command i see this:

```
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 473 suitable to search for matches
[1/473] Searching for ...
```

i was expecting to search 2 torrents which i added an hour ago, other than the 2 torrent there were no torrents added to rtorrent in the last 48 hours,
why is cross-seed searching all my torrent?

this happened to me a few times before, the next day when i run the command everything works as expected again.

any idea what could cause this?

edit:
when i use  --exclude-older 120

```
cross-seed search --exclude-older 120
Validating your configuration...
Your configuration is valid!
Found 933 torrents, 2 suitable to search for matches
[1/2] Searching for ...
```

it works fine

### LINKED ISSUE #202: Switch cache to SQLite
when I run the cross seed script with many/all indexers I notice massive amounts of slowdown and constant ~80mb/s disk writes.
when I run int verbose mode I can clearly see that making decisions takes about a second, this isn't surprising given my cache.json is 82.8mb on disk. 
I could clear this cache.. but there are some trackers that have a daily limit of how many .torrents you can download. I'd also be pulling a few thousand torrents down every time I did this.

to me this seems like it really should be moved to an sqlite database, it's just a lot of overhead to process a large json like this.

### PR DESCRIPTION
**Pull request by mmgoodnow**
closes #202 
closes #69 

- [x] figure out what to do about migrations
- [x] prod db
- [x] remove all usages of lowdb in code

### CODE REVIEW

**Comment by mmgoodnow** [comment]
@Jerrk the second and third bugs you found (cannot read property id of undefined, and UNIQUE constraint failed) should be fixed now. Let's take the remaining conversation to this PR as I'm getting lost navigating through all these issues 😄

**Comment by Jerrk** [comment]
The db is now created without errors on both of my servers :+1: 

they both have the same error while searching through the daemon though.

im calling the search with: `docker exec cross-seed cross-seed search`
```
[32m[32minfo[32m[39m: [1/6] Searching for ...
file:///usr/src/app/dist/decide.js:93
const { id } = await trx("searchee")
^

TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
at file:///usr/src/app/dist/decide.js:93:17
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
```
[32m[32minfo[32m[39m: [1/650] Searching for ...
[32m[32minfo[32m[39m: [2/650] Searching for ...
file:///usr/src/app/dist/decide.js:93
const { id } = await trx("searchee")
^

TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is undefined.
at file:///usr/src/app/dist/decide.js:93:17
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by mmgoodnow** [comment]
fixed that one as well!

**Comment by Jerrk** [comment]
looks all good for me currently

ill keep an eye out for any other errors

good job :grin:

**Pull request merged**
